resources:
  repositories:
    - repository: templates
      type: github
      name: bincrafters/templates
      endpoint: github

extends:
  template: azure-template.yml
  parameters:
    conanLoginUsername: $(CONAN_LOGIN_USERNAME)
    conanPassword: $(CONAN_PASSWORD)
    vsVersions: "14,16"
